// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DxPackRecv.proto

package com.serialize.test.pojo;
//生成的java bean序列化文件
public final class DxPackRecvProtoTest {
  private DxPackRecvProtoTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DxPackRecvProtoTest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:DxPackRecvProtoTest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string packId = 1;</code>
     */
    boolean hasPackId();
    /**
     * <code>required string packId = 1;</code>
     */
    String getPackId();
    /**
     * <code>required string packId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPackIdBytes();

    /**
     * <code>required string packType = 2;</code>
     */
    boolean hasPackType();
    /**
     * <code>required string packType = 2;</code>
     */
    String getPackType();
    /**
     * <code>required string packType = 2;</code>
     */
    com.google.protobuf.ByteString
        getPackTypeBytes();

    /**
     * <code>required string channelId = 3;</code>
     */
    boolean hasChannelId();
    /**
     * <code>required string channelId = 3;</code>
     */
    String getChannelId();
    /**
     * <code>required string channelId = 3;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>required string routeHist = 4;</code>
     */
    boolean hasRouteHist();
    /**
     * <code>required string routeHist = 4;</code>
     */
    String getRouteHist();
    /**
     * <code>required string routeHist = 4;</code>
     */
    com.google.protobuf.ByteString
        getRouteHistBytes();

    /**
     * <code>required string packRecvStat = 5;</code>
     */
    boolean hasPackRecvStat();
    /**
     * <code>required string packRecvStat = 5;</code>
     */
    String getPackRecvStat();
    /**
     * <code>required string packRecvStat = 5;</code>
     */
    com.google.protobuf.ByteString
        getPackRecvStatBytes();

    /**
     * <code>required string stateTime = 6;</code>
     */
    boolean hasStateTime();
    /**
     * <code>required string stateTime = 6;</code>
     */
    String getStateTime();
    /**
     * <code>required string stateTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getStateTimeBytes();
  }
  /**
   * Protobuf type {@code DxPackRecvProtoTest1}
   */
  public  static final class DxPackRecvProtoTest1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DxPackRecvProtoTest1)
      DxPackRecvProtoTest1OrBuilder {
    // Use DxPackRecvProtoTest1.newBuilder() to construct.
    private DxPackRecvProtoTest1(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private DxPackRecvProtoTest1() {
      packId_ = "";
      packType_ = "";
      channelId_ = "";
      routeHist_ = "";
      packRecvStat_ = "";
      stateTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DxPackRecvProtoTest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              packId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              packType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              channelId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              routeHist_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              packRecvStat_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              stateTime_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DxPackRecvProtoTest.internal_static_DxPackRecvProtoTest1_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DxPackRecvProtoTest.internal_static_DxPackRecvProtoTest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DxPackRecvProtoTest1.class, Builder.class);
    }

    public static final com.google.protobuf.Parser<DxPackRecvProtoTest1> PARSER =
        new com.google.protobuf.AbstractParser<DxPackRecvProtoTest1>() {
      public DxPackRecvProtoTest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DxPackRecvProtoTest1(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DxPackRecvProtoTest1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKID_FIELD_NUMBER = 1;
    private Object packId_;
    /**
     * <code>required string packId = 1;</code>
     */
    public boolean hasPackId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string packId = 1;</code>
     */
    public String getPackId() {
      Object ref = packId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string packId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPackIdBytes() {
      Object ref = packId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        packId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKTYPE_FIELD_NUMBER = 2;
    private Object packType_;
    /**
     * <code>required string packType = 2;</code>
     */
    public boolean hasPackType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string packType = 2;</code>
     */
    public String getPackType() {
      Object ref = packType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string packType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPackTypeBytes() {
      Object ref = packType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        packType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELID_FIELD_NUMBER = 3;
    private Object channelId_;
    /**
     * <code>required string channelId = 3;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string channelId = 3;</code>
     */
    public String getChannelId() {
      Object ref = channelId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTEHIST_FIELD_NUMBER = 4;
    private Object routeHist_;
    /**
     * <code>required string routeHist = 4;</code>
     */
    public boolean hasRouteHist() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string routeHist = 4;</code>
     */
    public String getRouteHist() {
      Object ref = routeHist_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          routeHist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string routeHist = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRouteHistBytes() {
      Object ref = routeHist_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        routeHist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKRECVSTAT_FIELD_NUMBER = 5;
    private Object packRecvStat_;
    /**
     * <code>required string packRecvStat = 5;</code>
     */
    public boolean hasPackRecvStat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string packRecvStat = 5;</code>
     */
    public String getPackRecvStat() {
      Object ref = packRecvStat_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packRecvStat_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string packRecvStat = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPackRecvStatBytes() {
      Object ref = packRecvStat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        packRecvStat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATETIME_FIELD_NUMBER = 6;
    private Object stateTime_;
    /**
     * <code>required string stateTime = 6;</code>
     */
    public boolean hasStateTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string stateTime = 6;</code>
     */
    public String getStateTime() {
      Object ref = stateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stateTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stateTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStateTimeBytes() {
      Object ref = stateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPackType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRouteHist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPackRecvStat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPackIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPackTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getChannelIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRouteHistBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPackRecvStatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStateTimeBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPackIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPackTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getChannelIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRouteHistBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPackRecvStatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStateTimeBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static DxPackRecvProtoTest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DxPackRecvProtoTest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DxPackRecvProtoTest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DxPackRecvProtoTest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DxPackRecvProtoTest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DxPackRecvProtoTest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DxPackRecvProtoTest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DxPackRecvProtoTest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DxPackRecvProtoTest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DxPackRecvProtoTest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DxPackRecvProtoTest1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DxPackRecvProtoTest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DxPackRecvProtoTest1)
        DxPackRecvProtoTest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DxPackRecvProtoTest.internal_static_DxPackRecvProtoTest1_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DxPackRecvProtoTest.internal_static_DxPackRecvProtoTest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DxPackRecvProtoTest1.class, Builder.class);
      }

      // Construct using com.serialize.test.pojo.DxPackRecvProtoTest.DxPackRecvProtoTest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        packType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        channelId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        routeHist_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        packRecvStat_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        stateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DxPackRecvProtoTest.internal_static_DxPackRecvProtoTest1_descriptor;
      }

      public DxPackRecvProtoTest1 getDefaultInstanceForType() {
        return DxPackRecvProtoTest1.getDefaultInstance();
      }

      public DxPackRecvProtoTest1 build() {
        DxPackRecvProtoTest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DxPackRecvProtoTest1 buildPartial() {
        DxPackRecvProtoTest1 result = new DxPackRecvProtoTest1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packId_ = packId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packType_ = packType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channelId_ = channelId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.routeHist_ = routeHist_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packRecvStat_ = packRecvStat_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stateTime_ = stateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DxPackRecvProtoTest1) {
          return mergeFrom((DxPackRecvProtoTest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DxPackRecvProtoTest1 other) {
        if (other == DxPackRecvProtoTest1.getDefaultInstance()) return this;
        if (other.hasPackId()) {
          bitField0_ |= 0x00000001;
          packId_ = other.packId_;
          onChanged();
        }
        if (other.hasPackType()) {
          bitField0_ |= 0x00000002;
          packType_ = other.packType_;
          onChanged();
        }
        if (other.hasChannelId()) {
          bitField0_ |= 0x00000004;
          channelId_ = other.channelId_;
          onChanged();
        }
        if (other.hasRouteHist()) {
          bitField0_ |= 0x00000008;
          routeHist_ = other.routeHist_;
          onChanged();
        }
        if (other.hasPackRecvStat()) {
          bitField0_ |= 0x00000010;
          packRecvStat_ = other.packRecvStat_;
          onChanged();
        }
        if (other.hasStateTime()) {
          bitField0_ |= 0x00000020;
          stateTime_ = other.stateTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackId()) {
          
          return false;
        }
        if (!hasPackType()) {
          
          return false;
        }
        if (!hasChannelId()) {
          
          return false;
        }
        if (!hasRouteHist()) {
          
          return false;
        }
        if (!hasPackRecvStat()) {
          
          return false;
        }
        if (!hasStateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DxPackRecvProtoTest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DxPackRecvProtoTest1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object packId_ = "";
      /**
       * <code>required string packId = 1;</code>
       */
      public boolean hasPackId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string packId = 1;</code>
       */
      public String getPackId() {
        Object ref = packId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string packId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPackIdBytes() {
        Object ref = packId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          packId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string packId = 1;</code>
       */
      public Builder setPackId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string packId = 1;</code>
       */
      public Builder clearPackId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packId_ = getDefaultInstance().getPackId();
        onChanged();
        return this;
      }
      /**
       * <code>required string packId = 1;</code>
       */
      public Builder setPackIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packId_ = value;
        onChanged();
        return this;
      }

      private Object packType_ = "";
      /**
       * <code>required string packType = 2;</code>
       */
      public boolean hasPackType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string packType = 2;</code>
       */
      public String getPackType() {
        Object ref = packType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string packType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPackTypeBytes() {
        Object ref = packType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          packType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string packType = 2;</code>
       */
      public Builder setPackType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string packType = 2;</code>
       */
      public Builder clearPackType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packType_ = getDefaultInstance().getPackType();
        onChanged();
        return this;
      }
      /**
       * <code>required string packType = 2;</code>
       */
      public Builder setPackTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packType_ = value;
        onChanged();
        return this;
      }

      private Object channelId_ = "";
      /**
       * <code>required string channelId = 3;</code>
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string channelId = 3;</code>
       */
      public String getChannelId() {
        Object ref = channelId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string channelId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelId = 3;</code>
       */
      public Builder setChannelId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelId = 3;</code>
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>required string channelId = 3;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        channelId_ = value;
        onChanged();
        return this;
      }

      private Object routeHist_ = "";
      /**
       * <code>required string routeHist = 4;</code>
       */
      public boolean hasRouteHist() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string routeHist = 4;</code>
       */
      public String getRouteHist() {
        Object ref = routeHist_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            routeHist_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string routeHist = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRouteHistBytes() {
        Object ref = routeHist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          routeHist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string routeHist = 4;</code>
       */
      public Builder setRouteHist(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        routeHist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string routeHist = 4;</code>
       */
      public Builder clearRouteHist() {
        bitField0_ = (bitField0_ & ~0x00000008);
        routeHist_ = getDefaultInstance().getRouteHist();
        onChanged();
        return this;
      }
      /**
       * <code>required string routeHist = 4;</code>
       */
      public Builder setRouteHistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        routeHist_ = value;
        onChanged();
        return this;
      }

      private Object packRecvStat_ = "";
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public boolean hasPackRecvStat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public String getPackRecvStat() {
        Object ref = packRecvStat_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packRecvStat_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPackRecvStatBytes() {
        Object ref = packRecvStat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          packRecvStat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public Builder setPackRecvStat(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packRecvStat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public Builder clearPackRecvStat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packRecvStat_ = getDefaultInstance().getPackRecvStat();
        onChanged();
        return this;
      }
      /**
       * <code>required string packRecvStat = 5;</code>
       */
      public Builder setPackRecvStatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packRecvStat_ = value;
        onChanged();
        return this;
      }

      private Object stateTime_ = "";
      /**
       * <code>required string stateTime = 6;</code>
       */
      public boolean hasStateTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string stateTime = 6;</code>
       */
      public String getStateTime() {
        Object ref = stateTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stateTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string stateTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStateTimeBytes() {
        Object ref = stateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stateTime = 6;</code>
       */
      public Builder setStateTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string stateTime = 6;</code>
       */
      public Builder clearStateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stateTime_ = getDefaultInstance().getStateTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string stateTime = 6;</code>
       */
      public Builder setStateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stateTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DxPackRecvProtoTest1)
    }

    // @@protoc_insertion_point(class_scope:DxPackRecvProtoTest1)
    private static final DxPackRecvProtoTest1 defaultInstance;static {
      defaultInstance = new DxPackRecvProtoTest1();
    }

    public static DxPackRecvProtoTest1 getDefaultInstance() {
      return defaultInstance;
    }

    public DxPackRecvProtoTest1 getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DxPackRecvProtoTest1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DxPackRecvProtoTest1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020DxPackRecv.proto\"\207\001\n\024DxPackRecvProtoTe" +
      "st1\022\016\n\006packId\030\001 \002(\t\022\020\n\010packType\030\002 \002(\t\022\021\n" +
      "\tchannelId\030\003 \002(\t\022\021\n\trouteHist\030\004 \002(\t\022\024\n\014p" +
      "ackRecvStat\030\005 \002(\t\022\021\n\tstateTime\030\006 \002(\tB.\n\027" +
      "com.serialize.test.pojoB\023DxPackRecvProto" +
      "Test"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DxPackRecvProtoTest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DxPackRecvProtoTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DxPackRecvProtoTest1_descriptor,
        new String[] { "PackId", "PackType", "ChannelId", "RouteHist", "PackRecvStat", "StateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
