server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://serverIP:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ENC(XDXniOss+RDreT20MwH1Xqipe3Yt9V6q)
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.serialize
  config-location: classpath:mybatis/mybatis-config.xml
# 数据库加密（用盐）
jasypt:
  encryptor:
    password: nmyswls